version: '3.9'

services:
  realworld-api:
    build: ./nest-api
    container_name: realworld-nest-api
    ports:
      - '3000:3000'
    command: npm run start:dev
    stdin_open: true
    tty: true
    volumes:
      - ./nest-api/src:/usr/src/app/src
    restart: unless-stopped
    networks:
      - realworld-api-network
    environment:
      - IS_TS_NODE=true
    depends_on:
      - realworld-db

  realworld-db:
    image: postgres:alpine3.19
    container_name: realworld-postgres-db
    restart: unless-stopped
    networks:
      - realworld-api-network
    volumes:
      - ./pg_project:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=realworld

  realworld-db-admin:
    image: dpage/pgadmin4
    container_name: realworld-db-admin
    restart: unless-stopped
    networks:
      - realworld-api-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@realworld.ru
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - '82:80'
    depends_on:
      - realworld-db

networks:
  realworld-api-network:
    driver: bridge
